from tkinter import *
t=Tk()
t.configure(background='lightgrey')
t.geometry('800x500')
l=Label(t,text="STUDENT MARK SHEET",fg='black',bg='lightgrey',font=100)
l.pack()
l.place(x=5,y=10)
n=Label(t,text="NAME",fg='black',bg='lightgrey')
n.pack()
n.place(x=5,y=79)
e=Entry(t,width=30)
e.pack()
e.place(x=50,y=75,height=30)
r=Label(t,text="Enrol No:",fg='black',bg='lightgrey')
r.pack()
r.place(x=250,y=79)
m=Entry(t,width=30)
m.pack()
m.place(x=310,y=75,height=30)
s=Label(t,text="SUBJECT",fg='white',bg='black',font=150,width=20)
s.pack()
s.place(x=5,y=125)
a=Label(t,text="MARKS",fg='white',bg='black',font=150,width=20)
a.pack()
a.place(x=193,y=125)
a=Label(t,text="GRADE",fg='white',bg='black',font=150,width=20)
a.pack()
a.place(x=193,y=125)
t.mainloop()